export const expectedReleaseCommands = [
  "npm test",
  "npm run test",
  "npx tsc --noEmit",
  "npm run smoke:marketing",
  "npm run dogfood:marketing",
  "npm run qa:marketing",
  "npm run studio:check",
  "npm run qa:studio",
  "npm run intelligence:check",
  "npm run qa:intelligence",
  "npm run import:check",
  "npm run weekly:check",
  "npm run qa:weekly",
  "npm run workspace:check",
  "npm run backup:check",
  "npm run qa:workspace",
  "npm run flows:check",
  "npm run rc:check",
  "npm run qa:flows",
  "npm run health:routes",
  "npm run build",
  "npm run health:routes:local"
];
