export const expectedReleaseRoutes = [
  ["/", "Marketing Intelligence OS"],
  ["/storyops", "StoryOps"],
  ["/campaigns", "Campanhas"],
  ["/operations", "Central Operacional"],
  ["/exports", "Export Center"],
  ["/safety", "Safety Center"],
  ["/qa", "QA"],
  ["/studio", "Content Studio"],
  ["/library", "Biblioteca Editorial"],
  ["/recording", "Planejamento de Gravacao"],
  ["/review", "Fila de Revisao"],
  ["/insights", "Insights"],
  ["/metrics", "Metricas Manuais"],
  ["/experiments", "Experimentos Editoriais"],
  ["/strategy", "Estrategia"],
  ["/weekly-review", "Fechamento Semanal"],
  ["/imports", "Importacoes Manuais"],
  ["/performance", "Performance"],
  ["/workspace", "Workspace"],
  ["/history", "Historico"],
  ["/runbook", "Runbook Semanal"],
  ["/settings", "Configuracoes Locais"],
  ["/audit-log", "Registro Operacional"],
  ["/command-center", "Command Center"],
  ["/flows", "Fluxos Guiados"],
  ["/flows/fechamento-semanal-completo", "Fechamento semanal completo"],
  ["/release", "Release Candidate"],
  ["/onboarding", "Primeiros Passos"]
] as const;
